# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LpXLjkaKVpa19B6oOZnQ6q6la75JnD9Z
"""

# Commented out IPython magic to ensure Python compatibility.
import math
import numpy as np
import pandas as pd
# %matplotlib inline
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
import plotly.graph_objects as go


#load dataset
df_tr = pd.read_csv('aug_train.csv')
df_te = pd.read_csv('aug_test.csv')

#information about given data
df_tr.head()
df_tr.shape

#checking null values in given dataset
df_tr.isnull().sum()

df_tr['company_size']=[1 if company_size=="<10"
                       else 2 if company_size=="10/49"
                       else 3 if company_size=="50-99"
                       else 4 if company_size=="100-500"
                       else 5 if company_size=="500-999"
                       else 6 if company_size=="1000-4999"
                       else 7 if company_size=="5000-9999"
                       else 8 if company_size=="10000+"
                       else 0 for company_size in df_tr["company_size"]]

experience_new = {'<1': 0, '>20': 21}
df_tr = df_tr.replace({"experience": experience_new})
df_tr['experience'].fillna(df_tr['experience'].median(), inplace=True)


df_tr['last_new_job'] = df_tr['last_new_job'].fillna("NA")
lnj = {'>4': 5, 'never': 6}
df_tr = df_tr.replace({"last_new_job": lnj})

df_tr['gender'] = df_tr['gender'].fillna("NA")
df_tr['company_type'].fillna(df_tr['company_type'].mode()[0], inplace=True)
df_tr['major_discipline'].fillna(df_tr['major_discipline'].mode()[0], inplace=True)
df_tr['education_level'].fillna(df_tr['education_level'].mode()[0], inplace=True)
df_tr['enrolled_university'].fillna(df_tr['enrolled_university'].mode()[0], inplace=True)

df_te['company_size']=[1 if company_size=="<10"
                       else 2 if company_size=="10/49"
                       else 3 if company_size=="50-99"
                       else 4 if company_size=="100-500"
                       else 5 if company_size=="500-999"
                       else 6 if company_size=="1000-4999"
                       else 7 if company_size=="5000-9999"
                       else 8 if company_size=="10000+"
                       else 0 for company_size in df_te["company_size"]]

experience_new = {'<1': 0, '>20': 21}
df_te = df_te.replace({"experience": experience_new})
df_te['experience'].fillna(df_te['experience'].median(), inplace=True)


df_te['last_new_job'] = df_te['last_new_job'].fillna("NA")
lnj = {'>4': 5, 'never': 6}
df_te = df_te.replace({"last_new_job": lnj})

df_te['gender'] = df_te['gender'].fillna("NA")
df_te['company_type'].fillna(df_te['company_type'].mode()[0], inplace=True)
df_te['major_discipline'].fillna(df_te['major_discipline'].mode()[0], inplace=True)
df_te['education_level'].fillna(df_te['education_level'].mode()[0], inplace=True)
df_te['enrolled_university'].fillna(df_te['enrolled_university'].mode()[0], inplace=True)


df_te.isnull().sum()